# Generated by Django 4.0 on 2021-12-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigurumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of the amigurumi', max_length=50)),
                ('authorship', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AmigurumiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('amigurumi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='amigurumis.amigurumi')),
            ],
        ),
    ]
