# Generated by Django 4.0 on 2021-12-27 17:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amigurumi',
            options={'ordering': ['name', 'authorship']},
        ),
        migrations.AlterField(
            model_name='amigurumi',
            name='authorship',
            field=models.BooleanField(default=False, help_text="If you're the author of the recipe"),
        ),
        migrations.AlterField(
            model_name='amigurumiimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
