# Generated by Django 4.0 on 2022-01-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumis', '0003_aboutinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigurumi',
            name='url',
            field=models.CharField(default='https://www.etsy.com/shop/thegardenofyarns', help_text='Enter url of the amigurumi', max_length=100),
        ),
    ]
